"use client";
import "./candidate-overview.css";
import { useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, Building2, FileCheck2, FileText, Heart, Sparkles, UsersRound, X } from "lucide-react";
import type { myData } from "@/lib/data";
import type { SkillView } from "@/lib/skill-tree.server";
import { skillHref } from "@/lib/skill-tree-catalog";
import { PathPointMark } from "./path-point-mark";
import { InteractiveProfile } from "./interactive-profile";
type Data = NonNullable<Awaited<ReturnType<typeof myData>>>;
type View = "overview" | "projects" | "route" | "university" | "profile";
type Primary = { title: string; body: string; label: string; href: string };
export function SupportBanner() { return <aside className="overview-support"><Sparkles size={25} aria-hidden="true"/><div><strong>Твоё развитие —<br/>наша поддержка</strong><p>Практика, новые идеи и поддержка<br className="wide-only"/> на каждом шаге.</p></div><Image src="/images/invision/overview/student-320.webp" alt="" width={320} height={326} className="overview-student"/><span className="overview-motto" aria-hidden="true">Больше<br/>чем образование <Heart size={24}/></span></aside>; }
export function CandidateOverview({ data, tree, primary, important, needsAnswer, navigate }: { data: Data; tree: SkillView; primary: Primary; important: boolean; needsAnswer: boolean; navigate: (view: View, hash?: string) => void }) {
  const [chat, setChat] = useState(false), [files, setFiles] = useState(false); const dialog = useRef<HTMLDialogElement>(null);
  const recommended = tree.nodes.find((n) => n.id === tree.recommendedId)!;
  const completed = tree.domains.reduce((sum, domain) => sum + domain.done, 0);
  const opened = tree.domains.filter((domain) => domain.done > 0);
  const app = data.application;
  function open(which: "chat" | "files") { setChat(which === "chat"); setFiles(which === "files"); dialog.current?.showModal(); }
  function close() { dialog.current?.close(); setChat(false); setFiles(false); }
  return <div className="reference-overview overview-v2">
    <div className="overview-lead-grid"><section className="overview-card overview-next" aria-label="Следующее важное действие"><div className="overview-next-surface"><span className="overview-task-mark"><FileCheck2 size={29}/></span><div className="overview-next-copy"><span className="overview-kicker">{needsAnswer ? "Нужен твой ответ" : important ? "Следующий шаг по заявке" : "Следующий шаг"}</span><h2>{primary.title}</h2><p className="overview-primary-description">{primary.body}</p><div className="overview-next-actions"><Link className="button primary" href={primary.href} onClick={(event) => { if (primary.href.startsWith("#")) { event.preventDefault(); navigate("university", primary.href); } }}>{primary.label}<ArrowRight size={18}/></Link><button className="overview-all-tasks" onClick={() => navigate(important ? "university" : "route")}>{important ? "Все сообщения" : "Дерево навыков"}<ArrowRight size={17}/></button></div></div><div className="overview-checklist-art" aria-hidden="true"><Image src="/images/invision/overview-v2/checklist-720.webp" alt="" width={720} height={960} sizes="(max-width: 700px) 160px, 270px"/><span className="overview-paper-note">Маленькие<br/>шаги —<br/>большие<br/>перемены <Heart size={15}/></span></div></div></section>
      <div className="overview-side"><section className="overview-card overview-progress"><div className="overview-card-heading"><h2>Мой прогресс</h2><button className="overview-link" onClick={() => navigate("route")}>Детали<ArrowRight size={16}/></button></div><div className="overview-progress-main"><div className="overview-ring" style={{ "--progress": `${tree.nodes.length ? completed / tree.nodes.length * 100 : 0}%` } as React.CSSProperties} aria-label={`${completed} из ${tree.nodes.length} шагов завершено`}><strong>{completed}<span>/{tree.nodes.length}</span></strong></div><div><h3>{completed ? "Развитие в действии" : "Выбери первый шаг"}</h3><p>{completed ? `Пройдено ${completed} шагов в дереве навыков.` : "Начни с интересной ситуации в дереве навыков."}</p></div></div><div className="overview-progress-facts"><button onClick={() => navigate("route")}><PathPointMark/><strong>{tree.balance}<span>U</span></strong><small>За учебные шаги</small></button><button onClick={() => navigate("route")}><span className="overview-icon peach"><BookOpen size={25}/></span><strong>{opened.length}<span>направления</span></strong><small>С сохранённым прогрессом</small></button></div></section>
      <section className="overview-card overview-coach"><h2><Sparkles size={26}/>Vision · AI-наставник</h2><p>Задай вопрос о следующем шаге или разберись в задании.</p><button className="overview-featured-question" onClick={() => open("chat")}><span>Что попробовать после «{recommended.title}»?</span><span className="overview-send"><ArrowRight size={20}/></span></button></section></div></div>
    <section className="overview-card overview-skill-summary"><div className="overview-card-heading"><h2>Древо навыков</h2><Link className="overview-link" href={skillHref()}>Перейти в дерево<ArrowRight size={16}/></Link></div><p className="overview-section-description">Следующий личный шаг: <Link href={skillHref(recommended.id)}>{recommended.title}</Link>. Продолжай в удобном темпе.</p></section>
    <div className="overview-work-grid"><section className="overview-card overview-project"><div className="overview-card-heading"><h2>Мои материалы</h2><button className="overview-link" onClick={() => navigate("projects")}>Открыть<ArrowRight size={16}/></button></div><div className="overview-project-content"><div className="overview-project-copy"><div className="overview-project-title"><span className="overview-icon lime"><FileText size={27}/></span><h3>{app?.materials.length ? `${app.materials.length} файла в заявке` : "Личные работы и файлы"}</h3></div><p className="overview-project-description">Отправленные материалы заявки и личный архив работ собраны отдельно. Комиссия видит только переданное с твоего согласия.</p><Link className="button secondary" href="/my?view=projects">Открыть материалы<ArrowRight size={18}/></Link></div><div className="overview-project-art" aria-hidden="true"><Image src="/images/invision/overview-v2/books-360.webp" alt="" width={360} height={480} sizes="(max-width:700px) 120px, 190px"/></div></div></section>
    <section className="overview-card overview-resources"><div className="overview-card-heading"><h2>Попробуй дальше</h2><button className="overview-link" onClick={() => navigate("route")}>Все направления<ArrowRight size={16}/></button></div><div className="overview-resource-list">{tree.nodes.filter((n) => n.state === "available" || n.state === "in_progress").slice(0,3).map((n, i) => <Link key={n.id} href={skillHref(n.id)} className="overview-resource"><span className={`overview-icon ${i === 1 ? "lime" : "blue"}`}>{i === 1 ? <UsersRound size={27}/> : <BookOpen size={27}/>}</span><div><span className="overview-resource-topic">{tree.domains.find((d) => d.id === n.domain)?.title}</span><h3>{n.title}</h3><p>{n.branch} · +{n.reward} U</p></div><span className="overview-round-link"><ArrowRight size={16}/></span></Link>)}</div></section></div>
    <section className="overview-useful"><h2>Полезно для поступления</h2><div className="overview-useful-grid"><a href="https://www.invisionu.education/ru" target="_blank" rel="noopener noreferrer" className="overview-useful-card"><span className="overview-icon lime"><Building2 size={27}/></span><span><strong>Университет</strong><small>Программы и возможности<br/>inVision U для тебя.</small></span><span className="overview-round-link"><ArrowRight size={16}/></span></a><button className="overview-useful-card" onClick={() => open("files")}><span className="overview-icon blue"><FileText size={27}/></span><span><strong>Материалы к заявке</strong><small>Посмотри отправленные<br/>файлы и сведения.</small></span><span className="overview-round-link"><ArrowRight size={16}/></span></button><button className="overview-useful-card" onClick={() => navigate("university")}><span className="overview-icon lime"><UsersRound size={27}/></span><span><strong>Связь с университетом</strong><small>Заявка, сообщения<br/>и следующие шаги.</small></span><span className="overview-round-link"><ArrowRight size={16}/></span></button></div></section>
    <aside className="overview-closing"><span className="overview-closing-note" aria-hidden="true">Ты развиваешься<br/>и это видно <Heart size={23}/></span><div><h2>Двигаемся дальше?</h2><p>Попробуй новую ситуацию, сохрани решение<br className="wide-only"/> и возвращайся к нему в своём темпе.</p></div><Link className="button" href={skillHref(recommended.id)}>Продолжить<ArrowRight size={18}/></Link></aside>
    <dialog ref={dialog} className="overview-dialog" onClose={() => { setChat(false); setFiles(false); }}><header><h2>{chat ? "Vision · Твой AI-наставник" : "Файлы заявки"}</h2><button className="icon-button" aria-label="Закрыть" onClick={close}><X size={22}/></button></header>{chat && <InteractiveProfile scope={{}} title="Разобрать следующий шаг" initialOpen initialQuestion={`Что попробовать после «${recommended.title}»?`}/ >}{files && <div className="overview-reading-detail overview-files">{app?.materials.length ? <ul>{app.materials.map((file) => <li key={file.id}><a href={`/api/files/${file.id}`} target="_blank" rel="noopener noreferrer"><FileText size={20}/><span>{file.name}</span><ArrowRight size={16}/></a></li>)}</ul> : <p>В заявке пока нет файлов.</p>}<Link className="button secondary" href="/apply/status">Открыть заявку</Link></div>}</dialog>
  </div>;
}
