"use client";
import { useState } from "react";
import Image from "next/image";
import { cosmetics, postcards, questById, type CosmeticCategory } from "@/lib/world/progression";
import type { WorldAppearance, WorldState } from "@/lib/world/model";

type Mode="store"|"wardrobe"|"desk"|"quest";
type Action=(type:"world.purchase"|"world.appearance"|"world.display"|"world.quest",fields:Record<string,unknown>)=>Promise<string|null>;
const labels:Record<CosmeticCategory,string>={outfit:"Одежда",accessory:"Аксессуары",desk:"Для стола",world:"Для комнаты",display:"Для коллекции"};
const icon=(id:string)=><Image src={`/world/art/cosmetic-${id}.webp`} width={76} height={76} alt="" unoptimized/>;
export default function WorldProgression({mode,state,points,questId,onAction,onClose,onConversation}:{mode:Mode;state:WorldState;points:number;questId?:string;onAction:Action;onClose:()=>void;onConversation?:()=>void}) {
  const [category,setCategory]=useState<CosmeticCategory>("outfit");
  const [appearance,setAppearance]=useState<WorldAppearance>(state.appearance);
  const [display,setDisplay]=useState<string[]>(state.displayedItems);
  const [choice,setChoice]=useState<0|1|null>(null);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState("");
  const act=async(type:Parameters<Action>[0],fields:Record<string,unknown>)=>{setBusy(true);setMessage("");try{const result=await onAction(type,fields);if(result)setMessage(result);return Boolean(result)}finally{setBusy(false)}};
  const quest=questId?questById[questId]:null;
  const questStep=quest?state.sideQuests[quest.id]?.step??0:0;
  const isLast=Boolean(quest && questStep===quest.steps.length-1);
  return <div className="world-overlay" role="dialog" aria-modal="true" aria-label={mode==="store"?"Лавка кампуса":mode==="wardrobe"?"Гардероб":mode==="desk"?"Личный стол":"История кампуса"}><div className="world-progress-panel">
    <header><div><small>{mode==="store"?"CAMPUS SQUARE":mode==="quest"?"ИСТОРИЯ КАМПУСА":"МОЙ УГОЛОК"}</small><h2>{mode==="store"?"Лавка кампуса":mode==="wardrobe"?"Гардероб":mode==="desk"?"Личный стол":quest?.title}</h2></div><button type="button" onClick={onClose} aria-label="Закрыть">×</button></header>
    {mode==="store"&&<><p>Здесь U можно обменять на вещи для образа и личного уголка. Всё остаётся у тебя.</p><strong className="world-progress-balance">✦ {points} U</strong><div className="world-progress-tabs">{(Object.keys(labels) as CosmeticCategory[]).map(id=><button key={id} type="button" aria-pressed={category===id} onClick={()=>setCategory(id)}>{labels[id]}</button>)}</div><div className="world-progress-items">{cosmetics.filter(item=>item.category===category).map(item=>{const owned=state.ownedCosmetics.includes(item.id);return <article key={item.id}>{icon(item.id)}<div><strong>{item.title}</strong><p>{item.detail}</p></div><button disabled={busy||owned||points<item.price} onClick={()=>void act("world.purchase",{itemId:item.id})}>{owned?"Уже есть":`${item.price} U`}</button></article>})}</div><p className="world-progress-note">Вещи не влияют на заявку и решения комиссии.</p></>}
    {mode==="wardrobe"&&<><p>Выбери образ для прогулки. Базовые варианты всегда доступны.</p><div className="world-progress-wardrobe"><div className="world-progress-avatar" aria-hidden="true"><span/><small>Твой персонаж</small>{appearance.top&&icon(appearance.top)}{appearance.accessory&&icon(appearance.accessory)}</div><div className="world-progress-fields"><label>Основа<select value={appearance.preset} onChange={e=>setAppearance({...appearance,preset:e.target.value as WorldAppearance["preset"]})}><option value="classic">Классический</option><option value="cyan">Голубой</option><option value="graphite">Графитовый</option></select></label><label>Волосы<select value={appearance.hair} onChange={e=>setAppearance({...appearance,hair:e.target.value as WorldAppearance["hair"]})}><option value="short">Короткие</option><option value="wave">Волнистые</option><option value="curl">Кудри</option></select></label><label>Низ<select value={appearance.bottom} onChange={e=>setAppearance({...appearance,bottom:e.target.value as WorldAppearance["bottom"]})}><option value="graphite">Графитовый</option><option value="denim">Джинсовый</option><option value="olive">Оливковый</option></select></label><label>Верх<select value={appearance.top??""} onChange={e=>setAppearance({...appearance,top:e.target.value||null})}><option value="">Базовый</option>{cosmetics.filter(item=>item.category==="outfit"&&state.ownedCosmetics.includes(item.id)).map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Аксессуар<select value={appearance.accessory??""} onChange={e=>setAppearance({...appearance,accessory:e.target.value||null})}><option value="">Без аксессуара</option>{cosmetics.filter(item=>item.category==="accessory"&&state.ownedCosmetics.includes(item.id)).map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div></div><button className="world-progress-primary" disabled={busy} onClick={()=>void act("world.appearance",{appearance})}>Сохранить образ</button></>}
    {mode==="desk"&&<><p>Выбери до трёх вещей для своего уголка. Найденные открытки остаются в коллекции.</p><div className="world-progress-items">{cosmetics.filter(item=>["desk","world","display"].includes(item.category)&&state.ownedCosmetics.includes(item.id)).map(item=><button className="world-progress-display" key={item.id} aria-pressed={display.includes(item.id)} onClick={()=>setDisplay(prior=>prior.includes(item.id)?prior.filter(id=>id!==item.id):prior.length<3?[...prior,item.id]:prior)}>{icon(item.id)}<span>{item.title}</span></button>)}</div>{!state.ownedCosmetics.some(id=>cosmetics.some(item=>item.id===id&&["desk","world","display"].includes(item.category)))&&<p>В лавке кампуса есть вещи для этого стола.</p>}<h3>Открытки кампуса</h3><div className="world-progress-postcards">{state.postcards.length?state.postcards.map(id=>{const item=postcards[id];return item?<article key={id}><Image src={`/world/art/${item.art}.webp`} width={58} height={58} alt="" unoptimized/><strong>{item.title}</strong><small>{item.source??"История кампуса"} · {item.detail}</small></article>:null}):<p>Открытки появляются после небольших историй в районах.</p>}</div><button className="world-progress-primary" disabled={busy} onClick={()=>void act("world.display",{displayedItems:display})}>Расставить на столе</button></>}
    {mode==="quest"&&quest&&<><p className="world-progress-story">{questStep===0?quest.intro:quest.steps[questStep-1]?.story}</p><div className="world-progress-current"><small>СЕЙЧАС</small><strong>{quest.steps[questStep]?.prompt}</strong><p>Этот шаг продолжит историю в {quest.steps[questStep]?.point.scene==="square"?"Campus Square":"районе команды"}.</p></div>{isLast&&<fieldset className="world-progress-choices"><legend>Как закончить эту историю?</legend>{quest.endings.map((ending,index)=><label key={ending}><input type="radio" checked={choice===index} onChange={()=>setChoice(index as 0|1)}/>{ending}</label>)}</fieldset>}<div className="world-progress-actions"><button className="world-progress-primary" disabled={busy||isLast&&choice===null} onClick={()=>void act("world.quest",{questId:quest.id,...(isLast?{questChoice:choice}:{})})}>{isLast?"Завершить историю":"Продолжить историю"}</button>{onConversation&&<button onClick={onConversation}>Обычный разговор</button>}</div><small>За завершение: +{quest.reward} U{quest.postcard?" и открытка":""}</small></>}
    {message&&<p className="world-progress-message" role="status">{message}</p>}
  </div></div>;
}
