"use client";
import { useLayoutEffect, useRef, useState } from "react";
import Image from "next/image";
import { deeperChoices, newCondition, roles, type MissionPayload, type RoleId, type RoleProgress } from "@/lib/world/missions";

type Action = "intro" | "test" | "finish" | "deeper" | "replay" | "preference";
type Props = { roleId: RoleId; mode?: "main" | "deeper"; progress?: RoleProgress; hasComponent: boolean; onAction: (action: Action, payload: MissionPayload) => Promise<string | null>; onClose: () => void };
const options = {
  sensor: [["range","Дальний отклик · больше энергии"],["steady","Ровный отклик · средняя нагрузка"],["low-power","Простой отклик · меньше энергии"]],
  power: [["battery","Аккумулятор · быстро поставить"],["grid","Сеть · нужно уложить кабель"]],
  mount: [["open","Открытая сборка · всё видно"],["guarded","Кожух · безопаснее у края"]],
} as const;
const productCards = { schedule:"Расписание", place:"Как пройти", save:"Сохранить", detail:"Детали события" };
const policyCards = { demo:"Демонстрация", quiet:"Тихая зона", media:"Сцена", food:"Кофейная стойка" };
const mediaCards = { author:"Слова автора", schedule:"Программа", rumour:"Рассказ без подтверждения", photo:"Фото установки" };
const researchPeople = { volunteer:"Волонтёр у входа", visitor:"Гость с коротким маршрутом", quiet:"Гость, искавший тихое место", organizer:"Организатор" };
const storyCards = { scene:"Что изменилось на площадке", fact:"Что подтвердили участники", context:"Как это скажется на гостях" };
const pick = (current:string[], item:string, limit:number) => current.includes(item) ? current.filter((id)=>id!==item) : current.length<limit ? [...current,item] : current;

function ChoiceRow({value,items,onChange}:{value:string;items:readonly (readonly [string,string])[];onChange:(value:string)=>void}) {
  return <div className="world-mission-options">{items.map(([id,label])=><button type="button" key={id} className={value===id?"chosen":""} aria-pressed={value===id} onClick={()=>onChange(id)}>{label}</button>)}</div>;
}
function OrderBoard({items,labels,onChange}:{items:string[];labels:Record<string,string>;onChange:(items:string[])=>void}) {
  return <ol className="world-mission-order">{items.map((id,index)=><li key={id}><span>{index+1}</span><strong>{labels[id]}</strong><button type="button" aria-label={`Поднять ${labels[id]}`} disabled={!index} onClick={()=>{const next=[...items];[next[index-1],next[index]]=[next[index],next[index-1]];onChange(next);}}>↑</button><button type="button" aria-label={`Опустить ${labels[id]}`} disabled={index===items.length-1} onClick={()=>{const next=[...items];[next[index+1],next[index]]=[next[index],next[index+1]];onChange(next);}}>↓</button></li>)}</ol>;
}

export default function WorldMission({roleId,mode="main",progress,hasComponent,onAction,onClose}:Props) {
  const role=roles[roleId];
  const panelRef=useRef<HTMLDivElement>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const first=progress?.first?.choices;
  const [intro,setIntro]=useState(""),[sensor,setSensor]=useState(String(first?.sensor??"steady")),[power,setPower]=useState(String(first?.power??"battery")),[mount,setMount]=useState(String(first?.mount??"guarded"));
  const [connections,setConnections]=useState<string[]>(first?.connections as string[]??[]);
  const [flow,setFlow]=useState(first?.flow as string[] ?? ["schedule","place","detail","save"]),[problem,setProblem]=useState(String(first?.problem??"wayfinding"));
  const [testers,setTesters]=useState<string[]>(first?.testers as string[]??[]);
  const [interviews,setInterviews]=useState<string[]>(first?.interviews as string[]??[]),[hypothesis,setHypothesis]=useState(String(first?.hypothesis??"time"));
  const [evidence,setEvidence]=useState<string[]>(first?.evidence as string[]??["unclear","unclear"]);
  const [layout,setLayout]=useState(first?.layout as string[]??["demo","quiet","media","food"]),[priority,setPriority]=useState(String(first?.priority??"access"));
  const [volunteers,setVolunteers]=useState<string[]>(first?.volunteers as string[]??[]);
  const [sources,setSources]=useState<string[]>(first?.sources as string[]??[]),[angle,setAngle]=useState(String(first?.angle??"process")),[channel,setChannel]=useState(String(first?.channel??"board"));
  const [story,setStory]=useState(first?.story as string[]??["scene","fact","context"]),[headline,setHeadline]=useState(String(first?.headline??"making")),[updateChoice,setUpdateChoice]=useState("revise");
  const [deeperChoice,setDeeperChoice]=useState("");
  const stage=!progress?.introAt?"intro":progress.stage??"test";
  useLayoutEffect(()=>{if(panelRef.current) panelRef.current.scrollTop=0;},[stage,mode]);
  async function send(action:Action,payload:MissionPayload) {setBusy(true);setError("");const result=await onAction(action,payload);setBusy(false);if(result)setMessage(result);else setError("Действие не сохранено. Попробуй ещё раз после проверки соединения.");}
  function mainPayload():MissionPayload {return roleId==="engineer"?{sensor,power,mount,connections}:roleId==="product"?{flow,problem,testers}:roleId==="research"?{interviews,hypothesis,evidence}:roleId==="policy"?{layout,priority,volunteers}:{sources,angle,channel,story,headline,update:updateChoice};}
  function introPayload():MissionPayload {return roleId==="engineer"?{check:intro||"датчик"}:roleId==="product"?{flow:intro==="reverse"?["место","событие"]:["событие","место"]}:roleId==="research"?{question:intro||"как узнали о событии"}:roleId==="policy"?{zones:intro==="swap"?["проход","показ","тихая"]:["показ","тихая","проход"]}:{fact:intro||"место"};}
  if(mode==="deeper") return <div className="world-overlay world-mission-wrap" role="dialog" aria-modal="true" aria-label={role.deeper}><div className="world-mission"><header><div><small>ДВЕ КОМАНДЫ · {role.title.toUpperCase()}</small><h2>{role.deeper}</h2></div><button onClick={onClose} aria-label="Вернуться в мир">×</button></header><div className="world-mission-body"><div className="world-mission-illustration"><Image src={`/world/art/mission-${roleId}.webp`} width={192} height={192} alt="" unoptimized/><span>Другая сторона задачи</span></div><p className="world-mission-lead">Та же история затронула соседний район. Какой небольшой шаг ты предложишь команде?</p>{progress?.deeperAt?<div className="world-mission-test"><strong>В мире произошло</strong><p>{progress.deeperResult}</p></div>:<><ChoiceRow value={deeperChoice} items={deeperChoices[roleId]} onChange={setDeeperChoice}/><button className="world-mission-primary" disabled={busy||!deeperChoice} onClick={()=>void send("deeper",{deeperChoice})}>{busy?"Сохраняем…":"Предложить команде"}</button></>}{message&&<p role="status" className="world-mission-message">{message}</p>}{error&&<p role="alert" className="world-mission-warning">{error}</p>}</div></div></div>;
  return <div className="world-overlay world-mission-wrap" role="dialog" aria-modal="true" aria-label={role.mission}>
    <div className="world-mission" ref={panelRef}>
      <header><div><small>FESTIVAL OF IDEAS · {role.title.toUpperCase()}</small><h2>{stage==="intro"?role.intro:role.mission}</h2></div><button type="button" aria-label="Вернуться в мир" onClick={onClose}>×</button></header>
      <div className="world-mission-body">
        <div className="world-mission-illustration"><Image src={`/world/art/mission-${roleId}.webp`} width={192} height={192} alt="" unoptimized/><span>{role.scene === "maker" ? "Maker Yard" : role.scene === "garage" ? "Product Garage" : role.scene === "people" ? "People Lab" : role.scene === "urban" ? "Urban Lab" : "Media House"}</span></div>
        {stage==="intro" && <><p className="world-mission-lead">{role.lead==="aida"?"Аида передаёт тебе небольшой прототип: прежде чем менять всю установку, проверь одну деталь.":role.lead==="ayan"?"Аян показывает два экрана. Порядок меняет то, что гость заметит первым.":role.lead==="leila"?"Лейла просит не угадывать причину. Начни с вопроса, который даст наблюдение.":role.lead==="zhanerke"?"Жанерке оставила три элемента на макете. Проход должен остаться видимым.":"Иная готовит короткое объявление. Начни с факта, который можно сверить."}</p>
          {roleId==="engineer"&&<ChoiceRow value={intro} onChange={setIntro} items={[["датчик","Проверить датчик"],["крепление","Проверить крепление"]]}/>}
          {roleId==="product"&&<ChoiceRow value={intro} onChange={setIntro} items={[["normal","Сначала событие"],["reverse","Сначала место"]]}/>}
          {roleId==="research"&&<ChoiceRow value={intro} onChange={setIntro} items={[["как узнали о событии","Как узнали о событии?"],["почему не пришли","Что помешало прийти?"]]}/>}
          {roleId==="policy"&&<ChoiceRow value={intro} onChange={setIntro} items={[["normal","Показ · тихая зона · проход"],["swap","Проход · показ · тихая зона"]]}/>}
          {roleId==="media"&&<ChoiceRow value={intro} onChange={setIntro} items={[["место","Сверить место"],["время","Сверить время"]]}/>}
          <button className="world-mission-primary" disabled={busy} onClick={()=>void send("intro",introPayload())}>{busy?"Сохраняем…":"Попробовать · +25 U"}</button></>}
        {(stage==="test"||stage==="revision")&&<><p className="world-mission-lead">{stage==="test"?"Собери первую версию и проверь её. После испытания появится новое условие.":newCondition[roleId]}</p>
          {roleId==="engineer"&&<><div className="world-mission-art"><span>◉ ДАТЧИК</span><i/><span>▣ ПИТАНИЕ</span><i/><span>⬡ УСТАНОВКА</span></div><div className="world-mission-options">{[["sensor-power","Соединить датчик с питанием"],["power-mount","Соединить питание с установкой"]].map(([id,label])=><button type="button" key={id} aria-pressed={connections.includes(id)} className={connections.includes(id)?"chosen":""} onClick={()=>setConnections(v=>pick(v,id,2))}>{connections.includes(id)?"✓ ":"○ "}{label}</button>)}</div>{!hasComponent&&<p className="world-mission-warning">Сначала возьми комплект у стойки Maker Yard. Он находится справа от прототипа.</p>}<label>Датчик<ChoiceRow value={sensor} onChange={setSensor} items={options.sensor}/></label><label>Питание<ChoiceRow value={power} onChange={setPower} items={options.power}/></label><label>Крепление<ChoiceRow value={mount} onChange={setMount} items={options.mount}/></label></>}
          {roleId==="product"&&<><p>Собери путь гостя. Порядок экранов влияет на то, сколько шагов понадобится для поиска площадки и сохранения события.</p><OrderBoard items={flow} labels={productCards} onChange={setFlow}/><label>Что исправить первым?<ChoiceRow value={problem} onChange={setProblem} items={[["wayfinding","Поиск площадки"],["saving","Сохранение события"]]}/></label><strong>Выбери двух тестеров</strong><div className="world-mission-options">{[["visitor","Гость: ищет площадку"],["volunteer","Волонтёр: сохраняет событие"],["one-hand","Гость: держит телефон одной рукой"]].map(([id,label])=><button key={id} type="button" className={testers.includes(id)?"chosen":""} aria-pressed={testers.includes(id)} onClick={()=>setTesters(v=>pick(v,id,2))}>{label}</button>)}</div></>}
          {roleId==="research"&&<><p>У тебя два коротких интервью. Выбери разные точки зрения и рабочую гипотезу.</p><div className="world-mission-cards">{Object.entries(researchPeople).map(([id,label])=><button type="button" className={interviews.includes(id)?"chosen":""} aria-pressed={interviews.includes(id)} key={id} onClick={()=>setInterviews(v=>pick(v,id,2))}><small>БЕСЕДА</small>{label}</button>)}</div><p className="world-mission-detail">{interviews.includes("volunteer")&&"Волонтёр: «Люди спрашивали, где вход». "}{interviews.includes("visitor")&&"Гость: «Я пришёл позже из-за занятий». "}{interviews.includes("quiet")&&"Гость: «У сцены было слишком шумно». "}{interviews.includes("organizer")&&"Организатор: «Мы ожидали больше людей из другого корпуса»."}</p><label>Рабочее объяснение<ChoiceRow value={hypothesis} onChange={setHypothesis} items={[["time","Не подошло время"],["route","Маршрут был непонятен"],["interest","Тема не заинтересовала"]]}/></label><div className="world-mission-evidence"><strong>Два наблюдения. Как они соотносятся с версией?</strong>{["Волонтёр слышал вопросы о входе","Один гость пришёл после занятий"].map((item,index)=><div key={item}><span>{item}</span><ChoiceRow value={evidence[index]} onChange={(value)=>setEvidence(current=>current.map((v,i)=>i===index?value:v))} items={[["supports","Поддерживает"],["contradicts","Противоречит"],["unclear","Пока неясно"]]}/></div>)}</div>{stage==="revision"&&<div className="world-mission-data"><strong>Небольшая выборка · 20 ответов</strong><span>Маршрут 8 · время 5 · шум 4 · другое 3</span><small>Это подсказка для следующего вопроса, не вывод обо всех гостях.</small></div>}</>}
          {roleId==="policy"&&<><p>Четыре зоны помещаются вокруг прохода. Меняй места кнопками; на телефоне работает касание.</p><OrderBoard items={layout} labels={policyCards} onChange={setLayout}/><div className="world-mission-grid" aria-label="План площади">{layout.map((id,index)=><div key={id}><small>Сектор {index+1}</small><strong>{policyCards[id as keyof typeof policyCards]}</strong></div>)}</div><label>Главное ограничение<ChoiceRow value={priority} onChange={setPriority} items={[["access","Доступный проход"],["capacity","Вместимость"],["noise","Тихое место"]]}/></label><strong>Два волонтёра. Где они нужны?</strong><div className="world-mission-options">{[["entrance","У входа"],["demo","На демонстрации"],["quiet","У тихой зоны"]].map(([id,label])=><button key={id} type="button" className={volunteers.includes(id)?"chosen":""} aria-pressed={volunteers.includes(id)} onClick={()=>setVolunteers(v=>pick(v,id,2))}>{label}</button>)}</div></>}
          {roleId==="media"&&<><p>Выбери два источника. Один рассказ пока не подтверждён.</p><div className="world-mission-cards">{Object.entries(mediaCards).map(([id,label])=><button type="button" className={sources.includes(id)?"chosen":""} aria-pressed={sources.includes(id)} key={id} onClick={()=>setSources(v=>pick(v,id,2))}><small>{id==="rumour"?"НЕ ПРОВЕРЕНО":"ИСТОЧНИК"}</small>{label}</button>)}</div><strong>Собери последовательность истории</strong><OrderBoard items={story} labels={storyCards} onChange={setStory}/><label>Заголовок<ChoiceRow value={headline} onChange={setHeadline} items={[["making","Как команды готовят показ"],["visit","Куда прийти на фестивале"],["change","Почему показ изменился"]]}/></label><label>Угол истории<ChoiceRow value={angle} onChange={setAngle} items={[["process","Как создавали"],["visitor","Что увидит гость"],["change","Почему план изменился"]]}/></label><label>Канал<ChoiceRow value={channel} onChange={setChannel} items={[["board","Стенд на площади"],["social","Короткое сообщение"]]}/></label>{stage==="revision"&&<label>Поступил подтверждённый перенос. Что сделать?<ChoiceRow value={updateChoice} onChange={setUpdateChoice} items={[["revise","Обновить материал"],["clarify","Добавить уточнение"],["hold","Подождать полной сверки"]]}/></label>}</>}
          {stage==="revision"&&progress?.first&&<div className="world-mission-test"><small>ПЕРВАЯ ПРОБА</small><p>{progress.first.observation}</p><strong>{newCondition[roleId]}</strong></div>}
          <button className="world-mission-primary" disabled={busy||roleId==="engineer"&&!hasComponent} onClick={()=>void send(stage==="test"?"test":"finish",mainPayload())}>{busy?"Сохраняем…":stage==="test"?"Запустить испытание":"Сохранить новое решение"}</button>
        </>}
        {stage==="complete"&&<div className="world-mission-recap"><small>ЧТО ПРОИЗОШЛО</small><p>{progress?.final?.observation}</p><h3>Твой выбор и его цена</h3><p>{progress?.final?.consequence}</p><p>Можно вернуться и проверить другую версию. Первая история останется в личном журнале.</p><strong>{progress?.replayCount?"За повторное прохождение U не начисляются":`За первое завершение начислено ${role.mainReward} U`}</strong><div className="world-program"><small>ГДЕ ЭТО ВСТРЕЧАЕТСЯ В INVISION U</small><strong>{role.program}</strong><ul>{role.programFacts.map((fact)=><li key={fact}>{fact}</li>)}</ul><a href="https://www.invisionu.education/undergraduate" target="_blank" rel="noreferrer">Подробнее о программе</a></div><div className="world-mission-replay"><button onClick={()=>void send("replay",{})} disabled={busy}>Попробовать другой вариант</button><button onClick={onClose}>Вернуться в мир</button><a href={`/my?view=route&node=${role.skillNode}`}>Посмотреть в дереве</a></div><fieldset><legend>Как тебе было?</legend>{([["interested","Мне было интересно"],["again","Хочу попробовать ещё"],["not-for-me","Пока не моё"]] as const).map(([id,label])=><button type="button" className={progress?.preference===id?"chosen":""} key={id} onClick={()=>void send("preference",{preference:id})}>{label}</button>)}</fieldset></div>}
        {message&&<p className="world-mission-message" role="status">{message}</p>}{error&&<p className="world-mission-warning" role="alert">{error}</p>}
      </div>
    </div>
  </div>;
}
